on:
    push:
        branches:
            - master
    workflow_dispatch:

jobs:
    commons:
        name: Build images for Wikimedia Commons
        runs-on: ubuntu-latest
        steps:
            -   name: Checkout repository
                uses: actions/checkout@v4

            -   name: Setup Node
                uses: actions/setup-node@v3
                with:
                    node-version: lts/*
                    cache: 'npm'

            -   name: Install dependencies
                run: npm ci

            -   name: Get SHA hash of download script
                id: download-script-sha
                run: echo "hash=$(sha256sum scripts/download.sh | cut -d ' ' -f 1)" >> $GITHUB_OUTPUT

            -   name: Cache shapefiles
                id: cache-shapefiles
                uses: actions/cache@v3
                env:
                  cache-name: ph-adm-shapefiles
                with:
                  path: data
                  key: download-script-${{ steps.download-script-sha.outputs.hash }}
                  enableCrossOsArchive: true

            -   if: ${{ steps.cache-shapefiles.outputs.cache-hit != 'true' }}
                name: Download data
                run: npm run download

            -   name: Build 10%
                run: npm run gen-percent 10

            -   name: Build 12k
                run: npm run gen-resolution 12329x16537

            -   name: Upload artifacts
                uses: actions/upload-artifact@v3
                with:
                    name: wikimedia-commons
                    path: out/*